### PR TITLE
Added commands and changed stuff

### PR DESCRIPTION
**Pull request by MarkChase3**
I added some commands 'cause this project seems cool. Just a go to line utility and a concatenate

### CODE REVIEW

**Comment by shourdev** [comment]
Thanks!

**Comment by MarkChase3** [comment]
Well, testing now I discovered that when we write on the middle we replace text, not insert. Some idea for ba able to replace and insert when needed?

**Comment by shourdev** [comment]
Sorry, I couldn't get what you mean?

**Comment by MarkChase3** [comment]
Try inputting 3 random lines and going back to the second with :gotoit. now type a longer line than before. It will overwrite the \n character. We could fix it by instead of just overwrite characters we insert them, like a str[:i] + input + str[i:] in python. But this generates other problem: What if we want to overwrite a line. don't matter what we try with the current commands, we can't change what's written.

**Comment by MarkChase3** [comment]
Found out that a little debug change don't put \n at the end of lines. Fixed it and some details.

**Pull request merged**
